# Site
repository: shribadiger/shrikant
favicon: images/favicon.ico

# Personal info
name: Shrikant Badiger
title: Senior Software Engineer
email: shrikant200@gmail.com
website: https://shribadiger.github.io/shrikant/

# Social links
twitter_username: facespics
github_username:  shribadiger
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: shrikantbadiger
linkedin_username: www.linkedin.com/in/ShrikantBadiger
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, 
  I am Shrikant Badiger working as Senior Developer in Siemens Technology and Service Pvt Ltd, Bangalore. I am having 8 Years
  of Experience in Telecom and Industrial Automation software development using C, C++, Python and Scripting Languaues. I am 
  interesetd in Object Oriented Programming Languages and Video and Image Processing using OpenCV and Python. 

  Skill : <mark> C / C++ Programming </mark>  & <mark> Docker / Kubernetes </mark> & <mask> Machine Learning </mask>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
