# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Shrikant Badiger
title: Senior Software Engineer
email: shrikant200@gmail.com
website: https://shribadiger.github.io/shrikant/

# Social links
twitter_username: facespics
github_username:  shribadiger
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: shrikantbadiger
linkedin_username: ShrikantBadiger
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Shrikant Badiger and I am a Senior Software Engineer in Siemens Technology-Bangalore. I am C, C++ and Python Programmer having 8 Years of Experience in development.

  Skill : <mark> C / C++ Programming </mark>  & <mark> Docker / Kubernetes </mark> & <mask> Machine Learning </mask>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
